item {
	name: 'rice'
	id: 1
}

item {
	name: 'eels_on_rice'
	id: 2
}

item {
	name: 'pilaf'
	id: 3
}

item {
	name: 'chicken_and_egg_on_rice'
	id: 4
}

item {
	name: 'pork_cutlet_on_rice'
	id: 5
}

item {
	name: 'beef_curry'
	id: 6
}

item {
	name: 'sushi'
	id: 7
}

item {
	name: 'chicken_rice'
	id: 8
}

item {
	name: 'fried_rice'
	id: 9
}

item {
	name: 'tempura_bowl'
	id: 10
}

item {
	name: 'bibimbap'
	id: 11
}

item {
	name: 'toast'
	id: 12
}

item {
	name: 'croissant'
	id: 13
}

item {
	name: 'roll_bread'
	id: 14
}

item {
	name: 'raisin_bread'
	id: 15
}

item {
	name: 'chip_butty'
	id: 16
}

item {
	name: 'hamburger'
	id: 17
}

item {
	name: 'pizza'
	id: 18
}

item {
	name: 'sandwiches'
	id: 19
}

item {
	name: 'udon_noodle'
	id: 20
}

item {
	name: 'tempura_udon'
	id: 21
}

item {
	name: 'soba_noodle'
	id: 22
}

item {
	name: 'ramen_noodle'
	id: 23
}

item {
	name: 'beef_noodle'
	id: 24
}

item {
	name: 'tensin_noodle'
	id: 25
}

item {
	name: 'fried_noodle'
	id: 26
}

item {
	name: 'spaghetti'
	id: 27
}

item {
	name: 'Japanese-style_pancake'
	id: 28
}

item {
	name: 'takoyaki'
	id: 29
}

item {
	name: 'gratin'
	id: 30
}

item {
	name: 'sauteed_vegetables'
	id: 31
}

item {
	name: 'croquette'
	id: 32
}

item {
	name: 'grilled_eggplant'
	id: 33
}

item {
	name: 'sauteed_spinach'
	id: 34
}

item {
	name: 'vegetable_tempura'
	id: 35
}

item {
	name: 'miso_soup'
	id: 36
}

item {
	name: 'potage'
	id: 37
}

item {
	name: 'sausage'
	id: 38
}

item {
	name: 'oden'
	id: 39
}

item {
	name: 'omelet'
	id: 40
}

item {
	name: 'ganmodoki'
	id: 41
}

item {
	name: 'jiaozi'
	id: 42
}

item {
	name: 'stew'
	id: 43
}

item {
	name: 'teriyaki_grilled_fish'
	id: 44
}

item {
	name: 'fried_fish'
	id: 45
}

item {
	name: 'grilled_salmon'
	id: 46
}

item {
	name: 'salmon_meuniere'
	id: 47
}

item {
	name: 'sashimi'
	id: 48
}

item {
	name: 'grilled_pacific_saury'
	id: 49
}

item {
	name: 'sukiyaki'
	id: 50
}

item {
	name: 'sweet_and_sour_pork'
	id: 51
}

item {
	name: 'lightly_roasted_fish'
	id: 52
}

item {
	name: 'steamed_egg_hotchpotch'
	id: 53
}

item {
	name: 'tempura'
	id: 54
}

item {
	name: 'fried_chicken'
	id: 55
}

item {
	name: 'sirloin_cutlet'
	id: 56
}

item {
	name: 'nanbanzuke'
	id: 57
}

item {
	name: 'boiled_fish'
	id: 58
}

item {
	name: 'seasoned_beef_with_potatoes'
	id: 59
}

item {
	name: 'hambarg_steak'
	id: 60
}

item {
	name: 'steak'
	id: 61
}

item {
	name: 'dried_fish'
	id: 62
}

item {
	name: 'ginger_pork_saute'
	id: 63
}

item {
	name: 'spicy_chili-flavored_tofu'
	id: 64
}

item {
	name: 'yakitori'
	id: 65
}

item {
	name: 'cabbage_roll'
	id: 66
}

item {
	name: 'egg_sunny-side_up'
	id: 68
}

item {
	name: 'natto'
	id: 69
}

item {
	name: 'cold_tofu'
	id: 70
}

item {
	name: 'egg_roll'
	id: 71
}

item {
	name: 'chilled_noodle'
	id: 72
}

item {
	name: 'stir-fried_beef_and_peppers'
	id: 73
}

item {
	name: 'simmered_pork'
	id: 74
}

item {
	name: 'boiled_chicken_and_vegetables'
	id: 75
}

item {
	name: 'sashimi_bowl'
	id: 76
}

item {
	name: 'sushi_bowl'
	id: 77
}

item {
	name: 'fish-shaped_pancake_with_bean_jam'
	id: 78
}

item {
	name: 'shrimp_with_chill_source'
	id: 79
}

item {
	name: 'roast_chicken'
	id: 80
}

item {
	name: 'steamed_meat_dumpling'
	id: 81
}

item {
	name: 'omelet_with_fried_rice'
	id: 82
}

item {
	name: 'cutlet_curry'
	id: 83
}

item {
	name: 'spaghetti_meat_sauce'
	id: 84
}

item {
	name: 'fried_shrimp'
	id: 85
}

item {
	name: 'potato_salad'
	id: 86
}

item {
	name: 'green_salad'
	id: 87
}

item {
	name: 'macaroni_salad'
	id: 88
}

item {
	name: 'Japanese_tofu_and_vegetable_chowder'
	id: 89
}

item {
	name: 'pork_miso_soup'
	id: 90
}

item {
	name: 'chinese_soup'
	id: 91
}

item {
	name: 'beef_bowl'
	id: 92
}

item {
	name: 'kinpira-style_sauteed_burdock'
	id: 93
}

item {
	name: 'rice_ball'
	id: 94
}

item {
	name: 'pizza_toast'
	id: 95
}

item {
	name: 'dipping_noodles'
	id: 96
}

item {
	name: 'hot_dog'
	id: 97
}

item {
	name: 'french_fries'
	id: 98
}

item {
	name: 'mixed_rice'
	id: 99
}

item {
	name: 'goya_chanpuru'
	id: 100
}

item {
	name: 'green_curry'
	id: 101
}

item {
	name: 'okinawa_soba'
	id: 102
}

item {
	name: 'mango_pudding'
	id: 103
}

item {
	name: 'almond_jelly'
	id: 104
}

item {
	name: 'jjigae'
	id: 105
}

item {
	name: 'dak_galbi'
	id: 106
}

item {
	name: 'dry_curry'
	id: 107
}

item {
	name: 'kamameshi'
	id: 108
}

item {
	name: 'rice_vermicelli'
	id: 109
}

item {
	name: 'paella'
	id: 110
}

item {
	name: 'tanmen'
	id: 111
}

item {
	name: 'kushikatu'
	id: 112
}

item {
	name: 'yellow_curry'
	id: 113
}

item {
	name: 'pancake'
	id: 114
}

item {
	name: 'champon'
	id: 115
}

item {
	name: 'crape'
	id: 116
}

item {
	name: 'tiramisu'
	id: 117
}

item {
	name: 'waffle'
	id: 118
}

item {
	name: 'rare_cheese_cake'
	id: 119
}

item {
	name: 'shortcake'
	id: 120
}

item {
	name: 'chop_suey'
	id: 121
}

item {
	name: 'twice_cooked_pork'
	id: 122
}

item {
	name: 'mushroom_risotto'
	id: 123
}

item {
	name: 'samul'
	id: 124
}

item {
	name: 'zoni'
	id: 125
}

item {
	name: 'french_toast'
	id: 126
}

item {
	name: 'fine_white_noodles'
	id: 127
}

item {
	name: 'minestrone'
	id: 128
}

item {
	name: 'pot_au_feu'
	id: 129
}

item {
	name: 'chicken_nugget'
	id: 130
}

item {
	name: 'namero'
	id: 131
}

item {
	name: 'french_bread'
	id: 132
}

item {
	name: 'rice_gruel'
	id: 133
}

item {
	name: 'broiled_eel_bowl'
	id: 134
}

item {
	name: 'clear_soup'
	id: 135
}

item {
	name: 'yudofu'
	id: 136
}

item {
	name: 'mozuku'
	id: 137
}

item {
	name: 'inarizushi'
	id: 138
}

item {
	name: 'pork_loin_cutlet'
	id: 139
}

item {
	name: 'pork_fillet_cutlet'
	id: 140
}

item {
	name: 'chicken_cutlet'
	id: 141
}

item {
	name: 'ham_cutlet'
	id: 142
}

item {
	name: 'minced_meat_cutlet'
	id: 143
}

item {
	name: 'thinly_sliced_raw_horsemeat'
	id: 144
}

item {
	name: 'bagel'
	id: 145
}

item {
	name: 'scone'
	id: 146
}

item {
	name: 'tortilla'
	id: 147
}

item {
	name: 'tacos'
	id: 148
}

item {
	name: 'nachos'
	id: 149
}

item {
	name: 'meat_loaf'
	id: 150
}

item {
	name: 'scrambled_egg'
	id: 151
}

item {
	name: 'rice_gratin'
	id: 152
}

item {
	name: 'lasagna'
	id: 153
}

item {
	name: 'Caesar_salad'
	id: 154
}

item {
	name: 'oatmeal'
	id: 155
}

item {
	name: 'fried_pork_dumplings_served_in_soup'
	id: 156
}

item {
	name: 'oshiruko'
	id: 157
}

item {
	name: 'muffin'
	id: 158
}

item {
	name: 'popcorn'
	id: 159
}

item {
	name: 'cream_puff'
	id: 160
}

item {
	name: 'doughnut'
	id: 161
}

item {
	name: 'apple_pie'
	id: 162
}

item {
	name: 'parfait'
	id: 163
}

item {
	name: 'fried_pork_in_scoop'
	id: 164
}

item {
	name: 'lamb_kebabs'
	id: 165
}

item {
	name: 'stir-fried_potato_with_eggplant_and_green_pepper'
	id: 166
}

item {
	name: 'roast_duck'
	id: 167
}

item {
	name: 'hot_pot'
	id: 168
}

item {
	name: 'pork_belly'
	id: 169
}

item {
	name: 'xiao_long_bao'
	id: 170
}

item {
	name: 'moon_cake'
	id: 171
}

item {
	name: 'custard_tart'
	id: 172
}

item {
	name: 'beef_noodle_soup'
	id: 173
}

item {
	name: 'pork_cutlet'
	id: 174
}

item {
	name: 'minced_pork_rice'
	id: 175
}

item {
	name: 'fish_ball_soup'
	id: 176
}

item {
	name: 'oyster_omelette'
	id: 177
}

item {
	name: 'glutinous_oil_rice'
	id: 178
}

item {
	name: 'trunip_pudding'
	id: 179
}

item {
	name: 'stinky_tofu'
	id: 180
}

item {
	name: 'lemon_fig_jelly'
	id: 181
}

item {
	name: 'khao_soi'
	id: 182
}

item {
	name: 'Sour_prawn_soup'
	id: 183
}

item {
	name: 'Thai_papaya_salad'
	id: 184
}

item {
	name: 'Hainan-style_chicken_with_marinated_rice'
	id: 185
}

item {
	name: 'fish_and_vegetable_ragout'
	id: 186
}

item {
	name: 'stir-fried_mixed_vegetables'
	id: 187
}

item {
	name: 'beef_in_oyster_sauce'
	id: 188
}

item {
	name: 'pork_satay'
	id: 189
}

item {
	name: 'spicy_chicken_salad'
	id: 190
}

item {
	name: 'noodles_with_fish_curry'
	id: 191
}

item {
	name: 'Pork_Sticky_Noodles'
	id: 192
}

item {
	name: 'Pork_with_lemon'
	id: 193
}

item {
	name: 'stewed_pork_leg'
	id: 194
}

item {
	name: 'charcoal-boiled_pork_neck'
	id: 195
}

item {
	name: 'fried_mussel_pancakes'
	id: 196
}

item {
	name: 'Deep_Fried_Chicken_Wing'
	id: 197
}

item {
	name: 'Barbecued_red_pork_in_sauce_with_rice'
	id: 198
}

item {
	name: 'Rice_with_roast_duck'
	id: 199
}

item {
	name: 'Rice_crispy_pork'
	id: 200
}

item {
	name: 'Wonton_soup'
	id: 201
}

item {
	name: 'Chicken_Rice_Curry_With_Coconut'
	id: 202
}

item {
	name: 'Crispy_Noodles'
	id: 203
}

item {
	name: 'Egg_Noodle_In_Chicken_Yellow_Curry'
	id: 204
}

item {
	name: 'coconut_milk_soup'
	id: 205
}

item {
	name: 'pho'
	id: 206
}

item {
	name: 'Hue_beef_rice_vermicelli_soup'
	id: 207
}

item {
	name: 'Vermicelli_noodles_with_snails'
	id: 208
}

item {
	name: 'Fried_spring_rolls'
	id: 209
}

item {
	name: 'Steamed_rice_roll'
	id: 210
}

item {
	name: 'Shrimp_patties'
	id: 211
}

item {
	name: 'ball_shaped_bun_with_pork'
	id: 212
}

item {
	name: 'Coconut_milk-flavored_crepes_with_shrimp_and_beef'
	id: 213
}

item {
	name: 'Small_steamed_savory_rice_pancake'
	id: 214
}

item {
	name: 'Glutinous_Rice_Balls'
	id: 215
}

item {
	name: 'loco_moco'
	id: 216
}

item {
	name: 'haupia'
	id: 217
}

item {
	name: 'malasada'
	id: 218
}

item {
	name: 'laulau'
	id: 219
}

item {
	name: 'spam_musubi'
	id: 220
}

item {
	name: 'oxtail_soup'
	id: 221
}

item {
	name: 'adobo'
	id: 222
}

item {
	name: 'lumpia'
	id: 223
}

item {
	name: 'brownie'
	id: 224
}

item {
	name: 'churro'
	id: 225
}

item {
	name: 'jambalaya'
	id: 226
}

item {
	name: 'nasi_goreng'
	id: 227
}

item {
	name: 'ayam_goreng'
	id: 228
}

item {
	name: 'ayam_bakar'
	id: 229
}

item {
	name: 'bubur_ayam'
	id: 230
}

item {
	name: 'gulai'
	id: 231
}

item {
	name: 'laksa'
	id: 232
}

item {
	name: 'mie_ayam'
	id: 233
}

item {
	name: 'mie_goreng'
	id: 234
}

item {
	name: 'nasi_campur'
	id: 235
}

item {
	name: 'nasi_padang'
	id: 236
}

item {
	name: 'nasi_uduk'
	id: 237
}

item {
	name: 'babi_guling'
	id: 238
}

item {
	name: 'kaya_toast'
	id: 239
}

item {
	name: 'bak_kut_teh'
	id: 240
}

item {
	name: 'curry_puff'
	id: 241
}

item {
	name: 'chow_mein'
	id: 242
}

item {
	name: 'zha_jiang_mian'
	id: 243
}

item {
	name: 'kung_pao_chicken'
	id: 244
}

item {
	name: 'crullers'
	id: 245
}

item {
	name: 'eggplant_with_garlic_sauce'
	id: 246
}

item {
	name: 'three_cup_chicken'
	id: 247
}

item {
	name: 'bean_curd_family_style'
	id: 248
}

item {
	name: 'salt_and_pepper_fried_shrimp_with_shell'
	id: 249
}

item {
	name: 'baked_salmon'
	id: 250
}

item {
	name: 'braised_pork_meat_ball_with_napa_cabbage'
	id: 251
}

item {
	name: 'winter_melon_soup'
	id: 252
}

item {
	name: 'steamed_spareribs'
	id: 253
}

item {
	name: 'chinese_pumpkin_pie'
	id: 254
}

item {
	name: 'eight_treasure_rice'
	id: 255
}

item {
	name: 'hot_and_sour_soup'
	id: 256
}

